### ISSUE TITLE
greyed out menu options are not distinguishable from others

### ISSUE THREAD

**Issue by ebbit1q** [mingomongo/DarkMingo-Theme-for-Cockatrice#1]
when you open a menu all the options have the same color, even though some of them might be disabled and not available, normally these are represented in a de-saturated grey to communicate that they are not available.

I'll add a screenshot later if needed.

**Comment by mingomongo** [comment]
Hey could you tell me where you're seeing this or upload a screenshot(s)? I can't seem to find a menu with this issue.

**Comment by ebbit1q** [comment]
![image](https://user-images.githubusercontent.com/36401181/129288752-7d599111-7767-402a-b737-a0690addad29.png)
original:
![image](https://user-images.githubusercontent.com/36401181/129288825-72a33259-e532-4563-a70f-067435ca1313.png)

**Comment by mingomongo** [comment]
Oh I'm sorry I misunderstood which menu you were talking about. This is actually a pretty big issue now I understand it! But thankfully it had a simple fix. A small update to the theme will come out today or the next few days with the fix and some small aesthetic changes. Thanks for reporting.

**Comment by ebbit1q** [comment]
sorry for the misunderstanding, the related qt class is called the QMenu.
looking forwards to the fix, thanks for maintaining the theme :+1:

**Comment by mingomongo** [comment]
Now fixed as of release of v1.2!
